### ISSUE TITLE
请问你的这个设备是什么CPU?

### ISSUE THREAD

**Issue by erquren** [eecn/ncnn-android-yolov8-pose#3]
我的晓龙865才3FPS

**Comment by eecn** [comment]
我就用的865，你可以试试模型的量化版本



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年06月14日 15:54 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [eecn/ncnn-android-yolov8-pose] 请问你的这个设备是什么CPU? (Issue #3) |

我的晓龙865才3FPS
