### ISSUE TITLE
AAPT: error: resource drawable/pose (aka com.tencent.yolov8ncnn:drawable/pose) not found

### ISSUE THREAD

**Issue by Myzhencai** [eecn/ncnn-android-yolov8-pose#4]
HI ,anyone have a idea to fix this :-)

![image](https://github.com/eecn/ncnn-android-yolov8-pose/assets/21084423/644359b9-5357-42be-9a34-8e9ed9115ac4)

![image](https://github.com/eecn/ncnn-android-yolov8-pose/assets/21084423/8db81df8-0e4f-4595-aba4-375b4edd4b35)

![image](https://github.com/eecn/ncnn-android-yolov8-pose/assets/21084423/df82bae7-f45c-49a1-8ef0-f091e769f2d1)

**Comment by yangwcwpt** [comment]
我帮大佬回一下吧，在图片中的文件，AndroidManifest.xml，第10行的位置，有一个android:icon="@drawable/pose">，应该是个图标，找不到，直接删掉就可以啦，注意 删android:icon="@drawable/pose"，不要把删  >
![1721188788085](https://github.com/user-attachments/assets/c806902d-e587-4581-a86a-23c3331eceaf)

**Comment by eecn** [comment]
add icon img
