### ISSUE TITLE
尝试转换yolov8m或者yolov8l转ncnn后做测试

### ISSUE THREAD

**Issue by jackspeed** [eecn/ncnn-android-yolov8-pose#5]
大佬  您好！请问下您有尝试转换yolov8m或者yolov8l转ncnn后做测试吗？我把yolov8l转ncnn后，用您这个项目跑会闪退。是不是我转的步骤有问题？请请教一下您是怎么转的呢。我使用官网的export转的：
from ultralytics import YOLO
model = YOLO("yolov8n-pose.pt")
model.export(format='ncnn', half=False, imgsz=640)

按这个步骤，转换出来的YOLOv8n、YOLOv8s都能成功运行，YOLOv8m/YOLOv8l加载后就闪退。
<img width="1493" alt="image" src="https://github.com/user-attachments/assets/ec03c1e1-58cb-4999-8501-dca6668c675e">

**Comment by eecn** [comment]
要扩展m或者l首先要在string.xml文件增加相应字段，然后在yolov8ncnn.cpp文件中Java_com_tencent_yolov8ncnn_Yolov8Ncnn_loadModel函数增加其对应的模型初始化实现。

**Comment by wuzengqun** [comment]
您好，为什么使用了您的模型和代码，放到手机上运行之后，帧率只有1-2帧，并且没有画出框，然后线段全部集中在左上角。这个项目对于不同的手机还需要做其它修改吗？我的手机是红米K20

**Comment by wuzengqun** [comment]
> 大佬 您好！请问下您有尝试转换yolov8m或者yolov8l转ncnn后做测试吗？我把yolov8l转ncnn后，用您这个项目跑会闪退。是不是我转的步骤有问题？请请教一下您是怎么转的呢。我使用官网的export转的： from ultralytics import YOLO model = YOLO("yolov8n-pose.pt") model.export(format='ncnn', half=False, imgsz=640)
> 
> 按这个步骤，转换出来的YOLOv8n、YOLOv8s都能成功运行，YOLOv8m/YOLOv8l加载后就闪退。 <img alt="image" width="1493" src="https://private-user-images.githubusercontent.com/15903549/355411413-ec03c1e1-58cb-4999-8501-dca6668c675e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1OTI2ODMsIm5iZiI6MTcyNDU5MjM4MywicGF0aCI6Ii8xNTkwMzU0OS8zNTU0MTE0MTMtZWMwM2MxZTEtNThjYi00OTk5LTg1MDEtZGNhNjY2OGM2NzVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDEzMjYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ODY0ZTE5MTk1MjkxNGEyYjA3ZDM1ZmQxZDFkZGExM2ZmMDczZTZkMjhmZTJlMzY3MTY0ZDBkMzFkNTdlZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yX274HI_mauO6zOymhPbqPnej8NicmS8FHU6wguOYfg">

哥啊，为什么我的环境里不能这样转换呢？请问需要特别安装什么吗？我在ncnn框架下转换就会有很多算子不支持
